name: Build Test

on:
  push:
    branches:
    - main
  release:
    types:
    - created
  pull_request:
    branches:
    - main

concurrency: build_test

jobs:
  build-release:
    name: Build Release on Windows
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v1
      - name: Initialize Submodules
        run: git submodule update --init --recursive
      - name: Define VERSION
        run: |
          $env:COMMIT = $env:GITHUB_SHA.Substring(0, 7)
          $env:REPO_NAME = $env:GITHUB_REPOSITORY -replace '.*/'
          $env:BRANCH = $env:GITHUB_REF -replace '.*/'
          ($env:REPO_NAME) >> VERSION
          ($env:BRANCH) >> VERSION
          ($env:COMMIT) >> VERSION
      - name: Build DotNet4 for Release
        run: |
          & "$Env:GITHUB_WORKSPACE\build.ps1"
      - name: Create Release
        uses: softprops/action-gh-release@91409e712cf565ce9eff10c87a8d1b11b81757ae
        env:
          GITHUB_TOKEN: ${{ secrets.AGITHUB_TOKEN }}
        with:
          files: src\Releases\**
          name: Release 1.0.0
          body_path:  RELEASE.md
          prerelease: true

  build:
    name: Build on Windows
    runs-on: windows-2022
    if: "!startsWith(github.ref, 'refs/tags/')"
    steps:
      - uses: actions/checkout@v1
      - name: Initialize Submodules
        run: git submodule update --init --recursive
      - name: Define VERSION
        run: |
          $env:COMMIT = $env:GITHUB_SHA.Substring(0, 7)
          $env:REPO_NAME = $env:GITHUB_REPOSITORY -replace '.*/'
          $env:BRANCH = $env:GITHUB_REF -replace '.*/'
          ($env:REPO_NAME) >> VERSION
          ($env:BRANCH) >> VERSION
          ($env:COMMIT) >> VERSION
      - name: Build DotNet6 Master
        run: |
          & "$Env:GITHUB_WORKSPACE\build.ps1"
      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: test-artifact
          path: src\bin\
